apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jkvf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jkvf
    app.kubernetes.io/part-of: ci10t-786-0026-app
  name: devfile-sample-jkvf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-jkvf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-jkvf
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0026-tenant/ci10t-786-0026-app/devfile-sample-jkvf@sha256:78afbde37314105e8dc50c0f4d1553c7aee3ac529b4b033247e4d45755320134
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
